project_name: NengoFPGA
pkg_name: nengo_fpga
repo_name: nengo/nengo-fpga

description: FPGA backend for Nengo
copyright_start: 2018

license_rst: {}

contributing_rst: {}

contributors_rst: {}

setup_cfg: {}

setup_py:
  package_data:
    nengo_fpga:
      - fpga_config
  entry_points:
    nengo.backends:
      - fpga = nengo_fpga:Simulator
  install_req:
    - nengo>=3.0.0
    - numpy>=1.13.0,<1.17
    - paramiko>=2.4.1
  docs_req:
    - sphinx>=1.8
    - jupyter
    - matplotlib>=1.4
    - nbsphinx
    - numpydoc>=0.6
    - nengo_sphinx_theme>=0.12.0
  tests_req:
    - pytest>=3.6
    - pytest-mock>=2.0
    - pytest-cov>=2.6

docs_conf_py:
  intersphinx_mapping:
    nengo-de1: "https://www.nengo.ai/nengo-de1/"
    nengo-pynq: "https://www.nengo.ai/nengo-pynq/"
  html_redirects:
    getting_started.html: getting-started.html
    examples/notebooks/00-communication_channel.html:
      examples/notebooks/00-communication-channel.html
    examples/notebooks/01-learn_communication_channel.html:
      examples/notebooks/01-learn-communication-channel.html
    examples/notebooks/02-set_neuron_params.html:
      examples/notebooks/02-set-neuron-params.html
    examples/notebooks/05-controlled_oscillator.html:
      examples/notebooks/05-controlled-oscillator.html
    examples/notebooks/06-chaotic_attractor.html:
      examples/notebooks/06-chaotic-attractor.html
  nengo_logo: nengo-fpga-full-light.svg
  nengo_logo_color: "#541a8b"

travis_yml:
  python: 3.6
  jobs:
    - script: static
    - script: test
    - script: remote-docs
  slack_notifications: "DO3CdeRII8IUEe+ao+ceg9+nSeVx9Vmc97h4Er5vuThH1EojnWjGwscAK0rD9aQ\
    9IpojQ7URk5lOKQYgBMEfoRLknOoq4V+IyH1KslXC9f3i3kVKIRA7q1TYWEoQW0lzc4PR0aWZBBTv/m8VqH\
    sWsw4QMXERvwimfxz7QNkTIFIEVdakAdE8ICdVjw8Kl17u5+vj/LHuc1m/Wgs/ruN8IfLfdLXlJj17/KvGy\
    uoJK9He366nStBkoU4xnGDi9Vl0mhzQRo/2Xe7FXGT/P2aUH93Awlj/Ucx4EmKypM+Bh/55OkKzZbSlvLyv\
    TqUJsaqjiCOiz7ZLJd4GFPLBPgIJ4yzIBzxOQGR1hh0BqNNDmXgqO3mexUpfaxkp5UCgusOyL5RkSLYUMcs\
    7NEDQNF9m6hLV+C6T6rQS95CTK+w/dohmyAeP506OPCpYpIqFDZYXR4Ah/Douyv4gKr7udzBAPo1ROqPpLd\
    pFTxOSHBd+BYX6BHvDBQ8rVY60tHax7LzCqKBEeJgMoVsTOG52KBSj+xSKWmrhXpXG7cCOOD5kfU/6/ayP+\
    xGjCBdmwHhbcWkKC3PlKu8sJnZMheeYTygUmQWZbzEBVPrPc/WcfKWDctXZ1DozhgF2siG/irLZ+MfACqKT\
    wE3ot5Vmib+f6kTlQEo3dXfKzSrWeR9fnqM6YvY="

ci_scripts:
  - template: static
  - template: test
    coverage: true
  - template: docs
    pip_install:
      - numpy>=1.13.0,<1.17
      - matplotlib
  - template: remote-script
    remote_script: docs
    output_name: remote-docs
    host: abrgl-ci
    travis_var_key: 2895d60e3414

codecov_yml: {}

pre_commit_config_yaml: {}

pyproject_toml: {}
