project_name: NengoFPGA
pkg_name: nengo_fpga
repo_name: nengo/nengo-fpga

description: FPGA backend for Nengo
copyright_start: 2018
license: abr-nonfree
main_branch: main

license_rst: {}

contributing_rst: {}

contributors_rst: {}

setup_cfg: {}

setup_py:
  package_data:
    nengo_fpga:
      - fpga_config
  entry_points:
    nengo.backends:
      - fpga = nengo_fpga:Simulator
  install_req:
    - nengo>=3.0.0
    - numpy>=1.13.0
    - paramiko>=2.4.1
  docs_req:
    - sphinx>=1.8
    - jupyter
    - matplotlib>=1.4
    - nbsphinx
    - numpydoc>=0.6
    - nengo_sphinx_theme>=0.12.0
  tests_req:
    - nengo[tests]>=3.0.0
    - pytest>=3.6
    - pytest-mock>=2.0
    - pytest-cov>=2.6

docs_conf_py:
  intersphinx_mapping:
    nengo-de1: "https://www.nengo.ai/nengo-de1/"
    nengo-pynq: "https://www.nengo.ai/nengo-pynq/"
  html_redirects:
    getting_started.html: getting-started.html
    examples/notebooks/00-communication_channel.html: examples/notebooks/00-communication-channel.html
    examples/notebooks/01-learn_communication_channel.html: examples/notebooks/01-learn-communication-channel.html
    examples/notebooks/02-set_neuron_params.html: examples/notebooks/02-set-neuron-params.html
    examples/notebooks/05-controlled_oscillator.html: examples/notebooks/05-controlled-oscillator.html
    examples/notebooks/06-chaotic_attractor.html: examples/notebooks/06-chaotic-attractor.html
  nengo_logo: nengo-fpga-full-light.svg
  nengo_logo_color: "#541a8b"

ci_scripts:
  - template: static
  - template: test
    coverage: true
  - template: docs
    pip_install:
      - numpy>=1.13.0
      - matplotlib
# this setup can be used to run CI scripts remotely over slurm:
#  - template: slurm-script
#    slurm_command: "srun -pCI"
#    wrapped_commands:
#      - sphinx-build
#    slurm_script: docs
#    output_name: slurm-docs
#  - template: remote-script
#    remote_script: slurm-docs
#    remote_setup:
#      - micromamba install -y pandoc ffmpeg
#    output_name: remote-docs
#    host: abrghost

pre_commit_config_yaml: {}

pyproject_toml: {}

version_py:
  major: 0
  minor: 2
  patch: 3
  release: false
